# This is because conform.lua uses `uvx yamlfix` to format YAML files.
# I don't want to start every YAML file with `---`
explicit_start = false

# Use 3 spaces for indentation instead of the default 2
# indent_mapping = 3    # indentation for mappings/dictionaries (default: 2)
# indent_sequence = 5   # indentation for sequences/lists (default: 4)
# indent_offset = 3     # indentation offset for elements (default: 2)
